- name: Stop WebDispatcher
  tags: stop,stop_webdisp
  remote_user: '{{sidadm}}'
  ansible.builtin.shell:
    cmd: 'sapcontrol -nr {{AS}} -function Stop'

- name: Start WebDispatcher
  tags: start,start_webdisp
  remote_user: '{{sidadm}}'
  ansible.builtin.shell:
    cmd: 'sapcontrol -nr {{AS}} -function Start'
