- name: Stop WebDispatcher
  tags: webdispatcher_stop,stop
  remote_user: '{{SID}}adm'
  ansible.builtin.shell:
    cmd: 'sapcontrol -nr {{INST}} -function Stop'

- name: Start WebDispatcher
  tags: webdispatcher_start,start
  remote_user: '{{SID}}adm'
  ansible.builtin.shell:
    cmd: 'sapcontrol -nr {{INST}} -function Start'
