---

- hosts: all
  become: true
  tasks: 
   
    ### Using module 'package' to install a package instead of zypper o apt  
  - name: Install Unzip
    package: 
      name: unzip

    ### Unarchiving a zip file from an specific source in this case a zip file in the web
  - name: Install terraform in application servers
    tags: app,application
    unarchive: 
      src: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_darwin_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    when: ansible_hostname == "managed1"

     ### Unarchiving a zip file from an specific source in this case a zip file in the web
  - name: Install terraform in application servers
    tags: db,database
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_darwin_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    when: ansible_hostname == "managed2" 
