---

- hosts: webdispatchers
  gather_facts: no
  remote_user: root
  roles:
    - role: WEBDISPATCHER
      sidadm: '{{SID|lower}}adm'

- hosts: as_abap
  gather_facts: no
  remote_user: root
  roles:
    - role: AS_ABAP
      sidadm: '{{SID|lower}}adm'
